version: "3.9"   
services:  
  webcsv:
    #build: .
    image: infracloudio/csvserver:v3
    environment:
      - CSVSERVER_BORDER=Orange
    command: ./csvserver
    ports:
      - "9393:9300"
  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
